set_property IOSTANDARD TMDS_33 [get_ports {TMDS_Clk_n_0}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_Clk_p_0}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_Data_n_0[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_Data_p_0[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_Data_n_0[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_Data_p_0[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_Data_n_0[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_Data_p_0[2]}]

set_property PACKAGE_PIN U20 [get_ports {TMDS_Clk_n_0}]
set_property PACKAGE_PIN T20 [get_ports {TMDS_Clk_p_0}]
set_property PACKAGE_PIN W16 [get_ports {TMDS_Data_n_0[0]}]
set_property PACKAGE_PIN V16 [get_ports {TMDS_Data_p_0[0]}]
set_property PACKAGE_PIN Y19 [get_ports {TMDS_Data_n_0[1]}]
set_property PACKAGE_PIN Y18 [get_ports {TMDS_Data_p_0[1]}]
set_property PACKAGE_PIN W20 [get_ports {TMDS_Data_n_0[2]}]
set_property PACKAGE_PIN V20 [get_ports {TMDS_Data_p_0[2]}]
